### Read all films
GET http://localhost:3000/films

### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read films with minimum duration of 170 minutes
GET {{baseUrl}}/films?minimum-duration=170

### Read film with id 3
GET {{baseUrl}}/films/3

### Add a new film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Zack Snyder's Justice League",
    "director": "Zack Snyder",
    "duration": 242
}

### Read films starting with "The"
GET {{baseUrl}}/films?starts-with=The

### Order films by duration 'asc'
GET {{baseUrl}}/films?order-by=duration

### Order films by title 'asc'
GET {{baseUrl}}/films?order-by=title

### Read films in page 1 with limit 3
GET {{baseUrl}}/films?page=1&limit=3

### Delete film with id 6
DELETE {{baseUrl}}/films/6

### Update film with id 3
PATCH {{baseUrl}}/films/3
Content-Type: application/json

{
    "imageUrl": "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg"
}

### Update film with id 3
PUT {{baseUrl}}/films/3
Content-Type: application/json

{
    "title": "Ze Darque Naïte",
    "director": "Kristofer Nolane",
    "duration": 180,
    "imageUrl": "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg"
}